import com.blamejared.gradle.mod.utils.GMUtils
import com.blamejared.gradle.mod.utils.values.GitChangelogValue
import net.darkhax.curseforgegradle.Constants as CFGConstants
import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'com.blamejared.loader-plugin'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric}"

    implementation "com.blamejared.searchables:Searchables-fabric-${minecraft}:${searchables}"
}

loom {
    def aw = project(':common').file("src/main/resources/${modid}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        named('client') {
            client()
            configName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run')
        }
    }
}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    dependsOn(tasks.jar)
    apiToken = GMUtils.locateProperty(project, 'curseforgeApiToken')

    def mainFile = upload(curse_project_id, tasks.jar.archiveFile)
    mainFile.changelogType = 'markdown'
    mainFile.changelog = providers.of(GitChangelogValue) {
        parameters.repository.set(git_repo)
    }.get()
    mainFile.releaseType = CFGConstants.RELEASE_TYPE_RELEASE
    mainFile.addJavaVersion("Java ${java_version}")
    mainFile.addGameVersion(minecraft)
    mainFile.addRequirement('fabric-api')
    mainFile.addRequirement('searchables')
    mainFile.addEnvironment('Client')
    doLast {
        project.ext.set('curse_file_url', "${curse_homepage}/files/${mainFile.curseFileId}")
    }
}

modrinth {
    token.set(GMUtils.locateProperty(project, 'modrinth_token'))
    projectId.set(modrinth_project_id)
    changelog.set(providers.of(GitChangelogValue) {
        parameters.repository.set(git_repo)
    }.get())
    versionName.set("Fabric-${minecraft}-$version")
    versionType.set('release')
    gameVersions.set([minecraft])
    uploadFile.set(tasks.jar)
    dependencies {
        required.project('fabric-api')
        required.project('searchables')
    }
}
tasks.modrinth.dependsOn(tasks.jar)

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}