group=com.blamejared.controlling
mod_name=Controlling
author=Jaredlll08
modid=controlling
avatar=https://media.forgecdn.net/avatars/49/603/636079972364045115.png
curse_project_id=250398
curse_homepage=https://www.curseforge.com/minecraft/mc-mods/controlling
modrinth_project_id=xv94TkTM
git_repo=https://github.com/jaredlll08/controlling
description=Adds the ability to search for keybinds using their name in the KeyBinding menu, this allows players to easily find a key binding in the menu.
item_icon=minecraft:compass

mod_version=26.2
java_version=25
minecraft=26.2
fabric_loader=0.19.3
fabric=0.152.1+26.2
neoforge=26.2.0.1-beta
neoforge_loader=[4,)
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

searchables=1.0.1
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false